Repository GiftForGood/website, pull requests merged in 2020-09, with the labels that each got.

#326 Add chat presence
  src/components/chat/modules/ChatDialogMessages.js
  utils/api/chats.js
  utils/firebase/index.js
Labels: priority.High

#332 Upgrade next to 9.5, add all public env vars with NEXT_PUBLIC_
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
  next.config.js
  package-lock.json
  package.json
  src/components/category/pages/DonationsViewCategoryPage.js
  src/components/category/pages/ViewAllDonationsPage.js
  src/components/category/pages/ViewAllWishesPage.js
  src/components/category/pages/WishesViewCategoryPage.js
  src/components/home/modules/TopDonations.js
  src/components/home/modules/TopWishes.js
  src/components/home/modules/algoliaHelpers.js
  src/components/imageContainers/ProfileAvatar.js
  src/components/search/modules/NavSearchBar.js
  src/components/search/modules/NavSearchBarDropdownList.js
  utils/admin-firebase/index.js
  utils/admin-firebase/server-cert.js
  utils/constants/thirdPartyAPIUrl.js
  utils/firebase/index.js
Labels: f.doNotMerge

#334 Add missing page links in drawer
  src/components/navbar/modules/TopNavigationBar.js
Labels: f.toMerge

#336 Fix search page bug
  src/components/search/pages/SearchPage.js
Labels: f.toMerge

#341 Fix/typos thru out website
  contents/blog/how-to-write-better-wishes.md
  contents/faq/faq.md
  src/components/card/DonorSessionCard.js
  src/components/register/modules/RegisterNpoDetails.js
Labels: f.toMerge
